# Generated by Django 4.2.3 on 2023-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('skills', models.TextField(max_length=1000)),
                ('about', models.TextField(max_length=500)),
                ('education', models.TextField(max_length=500)),
                ('work_experience', models.TextField(max_length=500)),
                ('interests', models.TextField(max_length=500)),
                ('open_source_projects', models.TextField(max_length=500)),
            ],
        ),
    ]
