# Generated by Django 4.2.3 on 2023-07-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.TextField(default='', max_length=500),
        ),
    ]
